import { getPayFastConfig } from "./config";
import { generatePayFastSignature } from "./signature";

export type PayFastPlan =
  | "STARTER"
  | "PROFESSIONAL"
  | "ENTERPRISE";

export type PayFastFrequency =
  | 1 // Daily
  | 2 // Weekly
  | 3 // Monthly
  | 4 // Quarterly
  | 5 // Biannually
  | 6; // Annual

export type PayFastCheckoutInput = {
  paymentReference: string;
  email: string;
  firstName: string;
  lastName: string;
  plan: PayFastPlan;
  amount: string;

  returnUrl: string;
  cancelUrl: string;
  notifyUrl: string;

  billingDate?: string;
  frequency?: PayFastFrequency;
  cycles?: number;
};

export type PayFastCheckout = {
  processUrl: string;
  fields: Record<string, string>;
};

/**
 * Valid LegalVault subscription plans.
 *
 * Runtime validation is required because TypeScript types
 * do not exist after compilation.
 */
const VALID_PLANS: readonly PayFastPlan[] = [
  "STARTER",
  "PROFESSIONAL",
  "ENTERPRISE",
];

/**
 * LegalVault currently uses monthly subscriptions.
 *
 * PayFast:
 * 1 = Daily
 * 2 = Weekly
 * 3 = Monthly
 * 4 = Quarterly
 * 5 = Biannually
 * 6 = Annual
 */
const LEGALVAULT_FREQUENCY: PayFastFrequency = 3;

/**
 * Validates the subscription plan at runtime.
 */
function validatePlan(
  plan: string,
): PayFastPlan {
  if (
    !VALID_PLANS.includes(
      plan as PayFastPlan,
    )
  ) {
    throw new Error(
      "Invalid LegalVault subscription plan.",
    );
  }

  return plan as PayFastPlan;
}

/**
 * Validates and normalises a monetary amount.
 *
 * Only positive values with no more than two decimal
 * places are accepted.
 */
function validateAmount(
  amount: string,
): string {
  const value =
    amount.trim();

  if (
    !/^\d+(?:\.\d{1,2})?$/.test(
      value,
    )
  ) {
    throw new Error(
      "PayFast payment amount must be a valid monetary value.",
    );
  }

  const numericAmount =
    Number(value);

  if (
    !Number.isFinite(
      numericAmount,
    ) ||
    numericAmount <= 0
  ) {
    throw new Error(
      "PayFast payment amount must be greater than zero.",
    );
  }

  if (
    numericAmount >
    999999999.99
  ) {
    throw new Error(
      "PayFast payment amount exceeds the supported maximum.",
    );
  }

  return numericAmount.toFixed(2);
}

/**
 * Trims a string and ensures it is not empty.
 */
function cleanRequiredValue(
  value: string,
  fieldName: string,
): string {
  const cleaned =
    value.trim();

  if (!cleaned) {
    throw new Error(
      `${fieldName} is required.`,
    );
  }

  return cleaned;
}

/**
 * Validates an email address.
 *
 * This is deliberately a basic application-level
 * validation. PayFast remains responsible for final
 * payment/customer validation.
 */
function validateEmail(
  email: string,
): string {
  const value =
    cleanRequiredValue(
      email,
      "PayFast email address",
    );

  if (
    value.length > 254
  ) {
    throw new Error(
      "PayFast email address is too long.",
    );
  }

  const emailPattern =
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  if (
    !emailPattern.test(value)
  ) {
    throw new Error(
      "PayFast email address is invalid.",
    );
  }

  return value;
}

/**
 * Validates a customer's name.
 */
function validateName(
  value: string,
  fieldName: string,
): string {
  const cleaned =
    cleanRequiredValue(
      value,
      fieldName,
    );

  if (
    cleaned.length > 100
  ) {
    throw new Error(
      `${fieldName} is too long.`,
    );
  }

  return cleaned;
}

/**
 * Validates the payment reference.
 *
 * LegalVault generates this value server-side.
 */
function validatePaymentReference(
  value: string,
): string {
  const reference =
    cleanRequiredValue(
      value,
      "PayFast payment reference",
    );

  if (
    reference.length > 100
  ) {
    throw new Error(
      "PayFast payment reference is too long.",
    );
  }

  /*
   * Only allow characters generated by LegalVault's
   * payment-reference generator.
   */
  if (
    !/^LV-PAY-\d+-[A-F0-9]+$/i.test(
      reference,
    )
  ) {
    throw new Error(
      "PayFast payment reference has an invalid format.",
    );
  }

  return reference;
}

/**
 * Validates an application URL.
 *
 * PayFast should only receive HTTP/HTTPS URLs.
 */
function validateUrl(
  value: string,
  fieldName: string,
): string {
  const cleaned =
    cleanRequiredValue(
      value,
      fieldName,
    );

  let parsedUrl: URL;

  try {
    parsedUrl =
      new URL(cleaned);
  } catch {
    throw new Error(
      `${fieldName} is invalid.`,
    );
  }

  if (
    parsedUrl.protocol !==
      "http:" &&
    parsedUrl.protocol !==
      "https:"
  ) {
    throw new Error(
      `${fieldName} must use HTTP or HTTPS.`,
    );
  }

  if (
    parsedUrl.username ||
    parsedUrl.password
  ) {
    throw new Error(
      `${fieldName} must not contain embedded credentials.`,
    );
  }

  return cleaned;
}

/**
 * Validates a real calendar date in YYYY-MM-DD format.
 */
function validateBillingDate(
  billingDate: string,
): string {
  const value =
    cleanRequiredValue(
      billingDate,
      "PayFast billing date",
    );

  if (
    !/^\d{4}-\d{2}-\d{2}$/.test(
      value,
    )
  ) {
    throw new Error(
      "PayFast billing date must use YYYY-MM-DD format.",
    );
  }

  const [year, month, day] =
    value
      .split("-")
      .map(Number);

  const date =
    new Date(
      Date.UTC(
        year,
        month - 1,
        day,
      ),
    );

  if (
    date.getUTCFullYear() !==
      year ||
    date.getUTCMonth() !==
      month - 1 ||
    date.getUTCDate() !==
      day
  ) {
    throw new Error(
      "PayFast billing date is not a valid calendar date.",
    );
  }

  return value;
}

/**
 * Validates PayFast subscription frequency.
 *
 * LegalVault currently supports monthly billing only.
 */
function validateFrequency(
  frequency: PayFastFrequency,
): string {
  if (
    frequency !==
    LEGALVAULT_FREQUENCY
  ) {
    throw new Error(
      "LegalVault currently supports monthly PayFast subscriptions only.",
    );
  }

  return String(
    frequency,
  );
}

/**
 * Validates PayFast subscription cycles.
 *
 * 0 = indefinitely recurring.
 */
function validateCycles(
  cycles: number,
): string {
  if (
    !Number.isInteger(
      cycles,
    ) ||
    cycles < 0
  ) {
    throw new Error(
      "PayFast subscription cycles must be zero or greater.",
    );
  }

  return String(
    cycles,
  );
}

/**
 * Creates the PayFast checkout payload.
 *
 * SECURITY PRINCIPLES:
 *
 * - Credentials come from server configuration.
 * - Amount is validated server-side.
 * - Plan is validated server-side.
 * - Payment reference is validated server-side.
 * - URLs are validated server-side.
 * - The PayFast signature is generated server-side.
 * - The passphrase is never exposed to the browser.
 */
export function createPayFastCheckout(
  input: PayFastCheckoutInput,
): PayFastCheckout {
  const config =
    getPayFastConfig();

  if (
    !config.passphrase
  ) {
    throw new Error(
      "A PayFast passphrase is required for recurring subscriptions.",
    );
  }

  const plan =
    validatePlan(
      input.plan,
    );

  const amount =
    validateAmount(
      input.amount,
    );

  const paymentReference =
    validatePaymentReference(
      input.paymentReference,
    );

  const email =
    validateEmail(
      input.email,
    );

  const firstName =
    validateName(
      input.firstName,
      "PayFast first name",
    );

  const lastName =
    validateName(
      input.lastName,
      "PayFast last name",
    );

  const returnUrl =
    validateUrl(
      input.returnUrl,
      "PayFast return URL",
    );

  const cancelUrl =
    validateUrl(
      input.cancelUrl,
      "PayFast cancel URL",
    );

  const notifyUrl =
    validateUrl(
      input.notifyUrl,
      "PayFast notify URL",
    );

  const billingDate =
    validateBillingDate(
      input.billingDate ??
        new Date(
          Date.now() +
            24 *
              60 *
              60 *
              1000,
        )
          .toISOString()
          .slice(0, 10),
    );

  const frequency =
    input.frequency ??
    LEGALVAULT_FREQUENCY;

  const cycles =
    input.cycles ?? 0;

  const validatedFrequency =
    validateFrequency(
      frequency,
    );

  const validatedCycles =
    validateCycles(
      cycles,
    );

  /*
   * For LegalVault's current subscription model,
   * the initial payment and recurring payment must
   * be identical.
   */
  const recurringAmount =
    amount;

  const fields: Record<
    string,
    string
  > = {
    merchant_id:
      config.merchantId,

    merchant_key:
      config.merchantKey,

    return_url:
      returnUrl,

    cancel_url:
      cancelUrl,

    notify_url:
      notifyUrl,

    name_first:
      firstName,

    name_last:
      lastName,

    email_address:
      email,

    m_payment_id:
      paymentReference,

    /*
     * Initial payment amount.
     */
    amount,

    item_name:
      `LegalVault ${plan} Subscription`,

    /*
     * PayFast recurring subscription.
     */
    subscription_type:
      "1",

    billing_date:
      billingDate,

    recurring_amount:
      recurringAmount,

    frequency:
      validatedFrequency,

    cycles:
      validatedCycles,

    subscription_notify_email:
      "true",

    subscription_notify_webhook:
      "true",

    subscription_notify_buyer:
      "true",
  };

  /*
   * IMPORTANT:
   *
   * The signature must be generated after every field
   * participating in the PayFast request has been added.
   *
   * The passphrase remains server-side and is never
   * returned in the checkout fields.
   */
  fields.signature =
    generatePayFastSignature(
      fields,
      config.passphrase,
    );

  return {
    processUrl:
      config.processUrl,

    fields,
  };
}